spring:
  version: @project.version@
  application:
    name: @project.artifactId@
    des: "Sonic云真机测试平台 - agent端"
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: @project.artifactId@,actuator,dubbo,feign,user,logging

sonic:
  saa: 2.0.0
  sgm: 0.1.9
  sib: 1.0.7