sonic:
  agent:
    host: 172.25.128.1
    port: 7777
    key: 29002272-4659-4808-a804-08ce3388b136
  server:
    host: 172.25.128.1
    folder-port: 8094
    transport-port: 8095

modules:
  android:
    enable: true
    use-adbkit: false
  ios:
    enable: false
    wda-bundle-id: com.sonic.wda.xctrunner
  appium:
    enable: true
  webview:
    enable: true
    chrome-driver-debug-port: 7778
    chrome-driver-path: C:\Program Files\Google\Chrome\Application\chromedriver.exe

logging:
  file:
    name: logs/sonic-agent.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 3
