sonic:
  agent:
    host: localhost
    port: 7777
    key: 7bbc50da-1c7b-43e7-9d5d-4e8a86fa896a
  server:
    host: localhost
    folder-port: 8094
    transport-port: 8095

modules:
  android:
    enable: true
  ios:
    enable: true
  webview:
    enable: true
    chrome-driver-path: "/Applications/Google Chrome.app/Contents/MacOS/chromedriver"

logging:
  file:
    name: logs/sonic-agent.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 3
