version: '3'
services:
  sonic-agent:
    image: "sonicorg/sonic-agent-linux:v1.4.1-alpha2"
    environment:
      # 对应server的env配置，注意防火墙关闭对应端口
      - SERVER_HOST=192.168.1.1
      - SONIC_GATEWAY_PORT=8094
      - SONIC_TRANSPORT_PORT=8095
      # 替换为部署Agent机器的ipv4
      - AGENT_HOST=192.168.1.1
      # 替换为Agent服务的端口，可以自行更改
      - AGENT_PORT=7777
      # 替换为前端新增Agent生成的key
      - AGENT_KEY=29002272-4659-4808-a804-08ce3388b136
      # 是否使用Sonic机柜，可以前往https://sonic-cloud.gitee.io/#/Cabinet了解更多
      - CABINET_ENABLE=true
      - CABINET_STOREY=1
      - CABINET_KEY=e33cd65c-a40e-431f-9e65-4a91bac6f487
      # 是否使用安卓模块
      - ANDROID_ENABLE=true
      # 是否开启远程adb调试功能
      - USE_ADBKIT=true
      # 是否使用iOS模块
      - IOS_ENABLE=true
      # 替换为你自己使用的wda的bundleId，如果没有.xctrunner后缀会自动补全，建议使用公司的开发者证书
      - WDA_BUNDLE_ID=com.facebook.WebDriverAgentRunner.xctrunner
      # 是否启用Appium
      - APPIUM_ENABLE=true
      # 是否启用webview调试功能
      - WEBVIEW_ENABLE=true
      # 谷歌调试端口，一般不需要修改（默认0使用随机端口，如果需要开启防火墙给外部使用，请设置固定端口如7778）
      - CHROME_DRIVER_PORT=0
      # 是否开启sonic-go-mitmproxy代理功能
      - SGM_ENABLE=true
    network_mode: "host"
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /var/run/usbmuxd:/var/run/usbmuxd