sonic:
  agent:
    # 替换为部署Agent机器的ipv4
    host: 192.168.1.8
    # 替换为Agent服务的端口，可以自行更改
    port: 7777
    # 替换为前端新增Agent生成的key
    key: 29002272-4659-4808-a804-08ce3388b136
  server:
    # 改成server的SERVER_HOST
    host: 192.168.1.8
    # 改成server的SERVER_PORT
    port: 8094

modules:
  android:
    # 是否开启安卓模块
    enable: true
    # 是否开启远程adb调试功能
    use-adbkit: true
  ios:
    # 如果不需要连接iOS设备，请将true改为false。开启的windows用户请确保本机已安装iTunes
    enable: true
    # 替换为你自己使用的wda的bundleId，如果没有.xctrunner后缀会自动补全，建议使用公司的开发者证书
    wda-bundle-id: com.sonic.WebDriverAgentRunner.xctrunner
  appium:
    # 是否开启Appium功能
    enable: true
  webview:
    # 是否开启在线webView调试功能
    enable: false
    # 谷歌调试端口，一般不需要修改（默认0使用随机端口，如果需要开启防火墙给外部使用，请设置固定端口如7778）
    chrome-driver-debug-port: 0
    # 替换为Agent机器上的chrome浏览器的driver路径，可以去http://npm.taobao.org/mirrors/chromedriver/下载
    chrome-driver-path: "/Applications/Google Chrome.app/Contents/MacOS/chromedriver"
  sgm:
    enable: false