sonic:
  agent:
    # 替换为部署Agent机器的ipv4
    host: ${AGENT_HOST:192.168.0.2}
    # 替换为Agent服务的端口，可以自行更改
    port: ${AGENT_PORT:7777}
    # 替换为前端新增Agent生成的key
    key: ${AGENT_KEY:235a35fd-5d0d-4533-905d-30d32902a12b}
  server:
    # 改成server的SERVER_HOST
    host: ${SERVER_HOST:192.168.1.1}
    # 改成server的SONIC_GATEWAY_PORT（一般不变）
    port: ${SONIC_GATEWAY_PORT:8094}
    # 改成server的SONIC_TRANSPORT_PORT（一般不变）
    transport-port: ${SONIC_TRANSPORT_PORT:8095}

modules:
  android:
    # 是否开启安卓模块
    enable: ${ANDROID_ENABLE:true}
    # 是否开启远程adb调试功能
    use-adbkit: ${USE_ADBKIT:true}
  ios:
    # 如果不需要连接iOS设备，请将true改为false。开启的windows用户请确保本机已安装iTunes
    enable: ${IOS_ENABLE:true}
    # 替换为你自己使用的wda的bundleId，如果没有.xctrunner后缀会自动补全，建议使用公司的开发者证书
    wda-bundle-id: ${WDA_BUNDLE_ID:com.facebook.WebDriverAgentRunner.xctrunner}
  appium:
    # 是否开启Appium功能
    enable: ${APPIUM_ENABLE:true}
  webview:
    # 是否开启在线webView调试功能
    enable: ${WEBVIEW_ENABLE:true}
    # 谷歌调试端口，一般不需要修改（默认0使用随机端口，如果需要开启防火墙给外部使用，请设置固定端口如7778）
    chrome-driver-debug-port: ${CHROME_DRIVER_PORT:0}
    # 替换为Agent机器上的chrome浏览器的driver路径，可以去http://npm.taobao.org/mirrors/chromedriver/下载
    chrome-driver-path: /usr/bin/chromedriver
  sgm:
    enable: ${SGM_ENABLE:true}