name: deploy to Dockerhub

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: login docker hub
        run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login -u zhouyixun --password-stdin
      - name: sgm-download
        uses: robinraju/release-downloader@v1.4
        with:
          repository: SonicCloudOrg/sonic-go-mitmproxy
          latest: true
          fileName: "*_linux_x86_64.tar.gz"
      - name: sgm
        run: tar zxvf *_linux_x86_64.tar.gz && rm *_linux_x86_64.tar.gz && mv sonic-go-mitmproxy plugins/sonic-go-mitmproxy
      - name: sib-download
        uses: robinraju/release-downloader@v1.4
        with:
          repository: SonicCloudOrg/sonic-ios-bridge
          latest: true
          fileName: "*_linux_x86_64.tar.gz"
      - name: sib
        run: tar zxvf *_linux_x86_64.tar.gz && rm *_linux_x86_64.tar.gz && mv sib plugins/sonic-ios-bridge
      - name: deploy
        run: mvn package -Plinux-x86_64 && docker build -t sonicorg/sonic-agent-linux:${{ steps.previoustag.outputs.tag }} -f src/main/docker/Dockerfile .
      - name: push
        run: docker push sonicorg/sonic-agent-linux:${{ steps.previoustag.outputs.tag }}
      - name: login docker hub
        run: echo "${{ secrets.ACCESS_TOKEN_ALIYUN }}" | docker login --username=小虫哔哔 registry.cn-hangzhou.aliyuncs.com --password-stdin
      - name: tag
        run: docker tag sonicorg/sonic-agent-linux:${{ steps.previoustag.outputs.tag }} registry.cn-hangzhou.aliyuncs.com/sonic-cloud/sonic-agent-linux:${{ steps.previoustag.outputs.tag }}
      - name: push
        run: docker push registry.cn-hangzhou.aliyuncs.com/sonic-cloud/sonic-agent-linux:${{ steps.previoustag.outputs.tag }}
